version: "3.3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - node.name=es01
      # - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
      ELASTICSEARCH_HOSTS: http://localhost:9200
    networks:
      - elastic
  logstach:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: log01
    networks:
      - elastic
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.6.2
  #   container_name: fil01
  #   networks:
  #     - elastic
volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
